version: '3.9'

networks:
 desafio-network:
  driver: bridge
  
services:
 db-api:
  image: postgres:10.23-alpine
  environment:
   POSTGRES_USER: dbamaster
   POSTGRES_PASSWORD: admin
   POSTGRES_DB: db-cadastro-pessoas
  ports:
   - "5432:5432"
  networks:
   - desafio-network
  volumes:
   - pg_data:/var/lib/postgresql/data/
 
 application:
  image: cadastro-pessoas
  command: catalina.sh run
  environment:
   DB_HOST: db-api
  ports:
   - "8080:8080"
  networks:
   - desafio-network
  depends_on:
   - db-api
   
volumes:
  pg_data:   